### ISSUE TITLE
Pulling shot statistics

### ISSUE THREAD

**Issue by garrettjj** [Dmitrii-I/sportmonks#1]
Hey there,

This project looks super great and I'm excited to take it for a spin. I was reading the documentation and was wondering if there is a way to probe for shots and shots on goal. I know that SportsMonks has these figures available although I wasn't sure if it was something that you had worked in here. It seems like this is likely a usage question rather than an issue or feature recommendation. 

Thanks,
Garrett J.

**Comment by Dmitrii-I** [comment]
Hi @garrettjj 

I searched around and I think that shots on goal and shots on target are available in the `trends` include. According to this [post by SportMonks](https://www.facebook.com/SP0RTM0NKS.C0M/posts/sportmonkscom-is-proud-to-announce-the-immediate-availability-of-trend-analyses-/551627025215923/) you need advanced data features in your plan. 

Assuming you have a SportMonks plan with advanced data features, getting the shots statistics for fixture with ID 123 would look like this:


    fixture_123 = api.fixture(fixture_id=123, includes=('trends',))

I do not have a plan with advanced features to test.
