### ISSUE TITLE
player endpoint should allow includes

### ISSUE THREAD

**Issue by burakuyar** [Dmitrii-I/sportmonks#7]
in sportmonks documentation this endpoint allows includes up to 2 levels. this should be allowed in the wrapper as well.

**Comment by burakuyar** [comment]
I have solved it in commit 8e0947c91fb50c6fb85a6033136a2ceccf73e6d3, you can directly take it.

**Comment by Dmitrii-I** [comment]
I reviewed https://docs.sportmonks.com/football/#players and you are right. I will implement this new feature and release version 1.1.0.

**Comment by Dmitrii-I** [comment]
Released version 1.1.0: https://pypi.org/project/sportmonks/
