### ISSUE TITLE
Think we need to include tzlocal as a requirement ?

### ISSUE THREAD

**Issue by eduardtm** [Dmitrii-I/sportmonks#9]
https://github.com/Dmitrii-I/sportmonks/blob/1b998c9c78155f4a076fbe55566f3b4bcc54f0c7/setup.py#L58

**Comment by Dmitrii-I** [comment]
@eduardtm Thanks for reporting! This is indeed a bug. I fixed it and released version 1.1.2. You can get it with `pip install sportmonks==1.1.2`.
